version: "3.9"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready","-d","postgres","-U","postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "homework"
    volumes:
      - ./src/main/resources/volumes/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    restart: always
  app:
    image:  bloodyt3ars/nexign-cdr:release
    restart: always
    container_name: nexign-cdr
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/homework
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
